# Generated by Django 5.2.5 on 2025-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('hirer', 'Hirer')], default='normal', max_length=20),
        ),
    ]
